---
title: "Resumen R - Curso de Estadistica Descriptiva"
output: html_notebook
---

# R Notebooks

Existe la opcion de previsualizar en panel de RStudio o en una ventana separada. Buscar en:
```
Tools -> Global Options -> R Markdown -> Show Output Preview In
```

- Ejecutar el chunk en el que esta el cursor: `⌘ + ⇧ + ⏎`. 
- Agregar un nuevo chunk de R: '⌘ + ⌥ + '.
- Previsualizar: '⌘ + ⇧ + k'


## Consola R Studio

- Ejecutar linea en la que esta el cursor: `⌘ + ⏎`
- Ejecutar todo el script: `⌘ + ⇧ + ⏎`
- Ejecutar todo el script sin echo: `⌘ + ⇧ + s`

valor de retorno del ultimo comando ejecutado
`.Last.value`


## Paquetes
```
install.packages("uno")
install.packages(c("uno","dos"))
library(uno)
```

Funciones
help(function)
?function
args(function)

Tipos de Datos
class(a)
integer, numeric, char, logical, vector, factors, lists, matrix, data.frame
1L       1        "aha" 1==1     c(1,2)

Vectors
codes <- c(404, 500, 501)
codes <- c(italy=380, canada=124, egypt=818)
codes[2]
codes[c(1,3)]
codes[1:2]
codes["canada"]
codes[c("egypt","italy")]

names(vector)
length(vector)
class(vector$columna)

# se pueden asignar nombres a un vector usando la funcion names
codes<-c(380,124,818)
country<-c("italy","canada","egypt)
names(codes)<-country

Factors
class(murders$region)
levels(murders$region)
length(murders$region)
table(murders$region

Reordenar factor por una columna
region <- murders$region
value <- murders$total
region <- reorder(region, value, FUN = sum)
levels(region)

Lists
record <- list(name=“John”, student_id=123, grades=c(94,24,64), final=“A”)
record$student_id
record[[“student_id”]]

Matrix
mat <- matrix(1:12, 4, 3)
mat[2, 3]
mat[2, ]
mat[ ,3]
mat[, 2:3]
mat[1:2, 2:3]
as.data.frame(mat)

## DataFrames
`View(dataframe)`

## Secuencias
Generador de Secuencias (funcion y operador)
```
seq(1,10,2) // 1 3 5 7 9
1:5 // 1 2 3 4 5
```

## Conversiones
as.integer
as.character
as.numeric

Sorting (sort, order, rank)

sort(murders$total) // 2 4 5 5 8 11 …
chars <- c("a", "c", "e", "b", "d")
idx <- order(chars) // 1 4 2 5 3
chars[idx] // “a” “b” “c” “d” “e”
max, min, which.max, which.min, rank

   x  <- 31  4 15 92 65
sort  ->  4 15 31 65 92
order ->  2  3  1  5  4
rank  ->  3  1  2  5  4

Indexing

# Which, Match, %in%
ind <- which(murders$state == “California”)
ind <- match(c(“New York”, “Florida”, “Texas”), murders$state)
c(“Boston”, “Dakota”) %in% murders$state // FALSE FALSE TRUE

# Equivalentes
states <- c(“Florida”, “Texas”)
match(states, murders$state)
which(murders$state %in% states)

# Indexing with logicals
murder_rate <- murders$total / murders$population * 1e5

# Equivalentes pero distintos
ind <- murder_rate < 0.71 // retorna vector logico del mismo tamaño que murder_rate
murders$state[ind]

ind <- which(murder_rate < 1) // retorna vector solamente con los indices que satisfacen
murders$state[ind]




